<a href="https://colab.research.google.com/github/hcgalvantech/proyecto_integrado_2xx/blob/main/Educacion_Argentina.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# prompt: armar un dataframe de al menos 100 filas con datos random con apellido y nombre, nro_dni, materias de educacion nivel secundario de la argentina que contenga las siguientes columnas: materia escolar, nota 1er Trimestre, nota 2do Trimestre, nota 3er Trimestre, Faltas a clases.

import pandas as pd
import numpy as np
import random

# Lista de materias escolares
materias = [
    "Matemática", "Lengua y Literatura", "Historia", "Geografía", "Ciencias Naturales",
    "Educación Física", "Inglés", "Física", "Química", "Biología", "Artes", "Música",
    "Filosofía", "Sociología", "Informática"
]

# Crear lista de apellidos y nombres ficticios
apellidos = ["García", "Rodríguez", "González", "Fernández", "López", "Martínez", "Pérez", "Gómez", "Sánchez", "Ramírez"]
nombres = ["Juan", "María", "Pedro", "Ana", "Luis", "Laura", "Carlos", "Sofía", "Diego", "Valentina"]

# Crear lista de DNI ficticios
dni = [random.randint(10000000, 99999999) for _ in range(100)]


# Función para generar datos aleatorios
def generar_datos():
  materia = random.choice(materias)
  nota_1er_trimestre = random.randint(1, 10)
  nota_2do_trimestre = random.randint(1, 10)
  nota_3er_trimestre = random.randint(1, 10)
  faltas = random.randint(0, 15)
  return materia, nota_1er_trimestre, nota_2do_trimestre, nota_3er_trimestre, faltas


# Crear una lista de diccionarios para el DataFrame
data = []
for i in range(100):
  apellido = random.choice(apellidos)
  nombre = random.choice(nombres)
  materia, nota_1er_trimestre, nota_2do_trimestre, nota_3er_trimestre, faltas = generar_datos()
  data.append({
      "Apellido": apellido,
      "Nombre": nombre,
      "Nro_DNI": dni[i],
      "Materia Escolar": materia,
      "Nota 1er Trimestre": nota_1er_trimestre,
      "Nota 2do Trimestre": nota_2do_trimestre,
      "Nota 3er Trimestre": nota_3er_trimestre,
      "Faltas a clases": faltas
  })


# Crear el DataFrame
df = pd.DataFrame(data)

# Mostrar el DataFrame
df

,Apellido,Nombre,Nro_DNI,Materia Escolar,Nota 1er Trimestre,Nota 2do Trimestre,Nota 3er Trimestre,Faltas a clases
0,Fernández,Carlos,99970338,Matemática,3,2,5,10
1,López,Carlos,16018754,Geografía,1,9,10,15
2,Fernández,Sofía,17690164,Química,9,4,2,13
3,Martínez,Pedro,42188259,Artes,8,6,10,6
4,Rodríguez,María,61716172,Matemática,7,5,6,5
...,...,...,...,...,...,...,...,...
95,Sánchez,Pedro,81028915,Biología,6,5,3,10
96,González,Carlos,23998327,Biología,10,2,6,1
97,Ramírez,Carlos,32883723,Lengua y Literatura,1,4,8,1
98,Ramírez,Luis,64257691,Matemática,6,10,10,8
99,Ramírez,Valentina,21370642,Geografía,4,8,2,7

In [2]:
df.to_csv("datos_alumnos.csv", index=False)